repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0        # ← use a tag that exists
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.9.1        # or whatever your Black version is
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-docstrings
